// 中文版：字幕文案与界面文字（界面文字与 App 中一致）。
(function () {
  const PV = (window.PV = window.PV || {});

  PV.copy = {
    lang: "zh",
    dlWidth: 640,
    title: "LightPlayer 宣传片",

    cap: {
      intro: ["每一首歌。", "每一部电影。", "每一句歌词。"],
      heroTitle: "轻，而无所不能。",
      heroSub: "一款为 Mac 打造的轻量多媒体播放器。",
      fmtTitle: "几乎所有格式，打开就能播。",
      fmtCols: [
        { t: "直接播放", d: "原生解码，零等待" },
        { t: "无损转封装", d: "视频流直接复制" },
        { t: "音频转换", d: "解码为 FLAC 缓存" },
        { t: "硬件实时转码", d: "硬件编码，流畅播放" },
      ],
      fmtFoot: "内置 FFmpeg，自动选择最合适的播放方式。",
      lyrTitle: "歌词，随歌声流动。",
      lyrSub: "逐字高亮，点按任意一句即可跳转。",
      aiTitle: "没有歌词？让它听一遍。",
      aiSub1: "基于 whisper.cpp 的本地离线识别，Apple 芯片 Metal 加速。",
      aiSub2: "你的音乐，从不离开你的 Mac。",
      dlTitle: "桌面歌词，浮于一切之上。",
      dlSub: "关掉窗口，音乐依然在菜单栏里继续。",
      wxTitle: "窗外的天气，也在窗内。",
      wxSub: "晴、雨、雪、雷电与星空，雨滴还会落在播放栏上。",
      libTitle: "整个音乐库，井然有序。",
      libSub: "按歌曲、专辑、艺术家与视频浏览，收藏和歌单随心整理。",
      vidTitle: "看电影，同样出色。",
      vidSub: "沉浸式全屏，AI 生成字幕，截图与逐帧步进。",
      moreTitle: "还有更多。",
      outroTag: "轻，而无所不能。",
      outroAvail: "适用于搭载 Apple 芯片的 Mac",
      outroUrl: "github.com/2001020/LightPlayer",
    },

    player: {
      start: "播放宣传片",
      play: "播放或暂停（空格）",
      mute: "声音（M）",
      fullscreen: "全屏（F）",
      record: "录制为视频文件",
      recording: "正在录制，点击停止",
      hint: "空格 播放或暂停　← → 快退快进　F 全屏",
      noRecord: "当前浏览器不支持录制。",
    },

    // 打开的歌曲
    song: {
      title: "浅蓝时刻",
      artist: "云野",
      album: "晴雨之间",
      file: "云野 - 浅蓝时刻.flac",
      ext: "FLAC",
      duration: 236,
    },

    // 原创歌词（words 为逐字时间轴的切分）
    lyrics: [
      "风把云朵吹成你的模样",
      "我在窗边等一场雨落下",
      "城市的灯一盏一盏亮起",
      "像你没说完的那句话",
      "浅蓝色的时刻 世界很安静",
      "我听见心跳和你的回声",
      "如果光能走得再慢一点",
      "我就能把今天唱给你听",
      "跟着旋律 走过晴雨之间",
      "每一句都刚好落在心上",
      "风停了 云还记得方向",
      "我们在歌里 慢慢发光",
    ],
    splitWords: (line) => Array.from(line),

    playlist: [
      "云野 - 浅蓝时刻",
      "云野 - 晴雨之间",
      "云野 - 云的形状",
      "云野 - 午后三点",
      "云野 - 远方来信",
      "云野 - 星期六的海",
      "云野 - 慢慢走",
      "云野 - 夜航",
      "云野 - 纸飞机",
      "云野 - 雾中城市",
    ],

    albums: [
      ["晴雨之间", "云野"],
      ["海岸线", "白鲸"],
      ["午夜电台", "林深"],
      ["夏日回声", "阿树"],
      ["纸飞机", "小满"],
      ["雾中城市", "北岛巡航"],
      ["霓虹之下", "夜行者"],
      ["远山", "青禾"],
      ["慢慢走", "南风"],
      ["星期六的海", "鲸落乐队"],
    ],

    songs: [
      ["浅蓝时刻", "云野", "晴雨之间", "3:56"],
      ["潮汐", "白鲸", "海岸线", "4:12"],
      ["凌晨两点的频率", "林深", "午夜电台", "3:41"],
      ["蝉鸣", "阿树", "夏日回声", "3:28"],
      ["纸飞机", "小满", "纸飞机", "3:05"],
      ["雾中城市", "北岛巡航", "雾中城市", "5:02"],
      ["霓虹之下", "夜行者", "霓虹之下", "4:20"],
      ["远山", "青禾", "远山", "3:47"],
      ["慢慢走", "南风", "慢慢走", "4:03"],
      ["星期六的海", "鲸落乐队", "星期六的海", "4:36"],
      ["云的形状", "云野", "晴雨之间", "3:33"],
      ["海风", "白鲸", "海岸线", "3:59"],
    ],

    video: {
      title: "海边日落",
      file: "海边日落 4K.mkv",
      strategy: "转封装播放",
      subs: ["海浪一遍又一遍地来", "像在重复同一句温柔的话", "天边的光慢慢落进海里"],
    },

    weather: { rain: "小雨", snow: "小雪", night: "晴" },

    menubar: {
      menus: ["文件", "编辑", "显示", "窗口", "帮助"],
      clock: "10月1日 周三 21:30",
      tray: ["浅蓝时刻 - 云野", "暂停", "上一首", "下一首", "无痕浏览模式", "显示 LightPlayer", "退出 LightPlayer"],
    },

    ui: {
      font: '"SF Pro Text", -apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Helvetica Neue", "Microsoft YaHei", "Noto Sans CJK SC", "Inter", "Noto Sans SC", "WenQuanYi Zen Hei", sans-serif',
      back: "返回",
      coverHint: "点击查看歌词",
      playlist: "播放列表",
      count: (n) => `${n} 首`,
      searchFolder: "搜索当前目录",
      fromFolder: "当前文件夹",
      handle: ["列", "表"],
      emptyTitle: "暂无歌词",
      emptyText: "没有在歌曲所在目录找到同名歌词文件",
      upload: "上传歌词文件",
      manual: "手动制作",
      aiRecognize: "AI 识别歌词",
      asrStage: "正在识别…",
      asrDecoding: "正在解码音频…",
      asrNote: "识别在本机离线进行，不会上传任何音频。歌曲较长时可能需要一两分钟，可以继续听歌。",
      viewAll: "查看全部任务",
      cancel: "取消",
      aiBanner: "本歌词由识别模型生成，可能有误",
      review: "校对编辑",
      rerun: "重新识别",
      remove: "移除",
      aiChip: "AI 歌词",
      nav: ["歌曲", "专辑", "艺术家", "视频", "收藏", "最近播放"],
      playlistsGroup: "歌单",
      userPlaylists: [["睡前慢歌", 24], ["通勤路上", 38], ["周末午后", 17]],
      manageFolders: "管理文件夹",
      search: "搜索标题、艺术家、专辑",
      playAll: "播放全部",
      shuffle: "随机播放",
      albumsTitle: "专辑",
      albumsSub: (n) => `${n} 张专辑`,
      songsTitle: "歌曲",
      songsSub: "1286 首，86 小时 12 分钟",
      cols: ["#", "标题", "艺术家", "专辑", "时长"],
      privateBadge: "无痕",
      dlColor: "文字颜色",
      speedLabel: "播放速度",
      normal: "正常",
    },

    tiles: [
      { icon: "ab", t: "A-B 段落循环", d: "反复聆听任意一段。", kind: "ab" },
      { icon: "speed", t: "倍速播放", d: "0.5× 到 3×，音调不变。", kind: "speed" },
      { icon: "timer", t: "睡眠定时", d: "到时渐弱，然后暂停。", kind: "timer" },
      { icon: "clock", t: "断点续播", d: "从上次停下的地方继续。", kind: "plain" },
      { icon: "incognito", t: "无痕浏览", d: "打开的文件不留下记录。", kind: "private" },
      { icon: "edit", t: "歌词编辑器", d: "边听边打点，逐行制作歌词。", kind: "editor" },
      { icon: "subtitles", t: "AI 视频字幕", d: "为任何视频生成字幕。", kind: "plain" },
      { icon: "camera", t: "视频截图", d: "一键保存当前画面。", kind: "plain" },
      { icon: "film", t: "逐帧步进", d: "按 , 与 . 一帧一帧地看。", kind: "frames" },
      { icon: "image", t: "随封面变色", d: "主题色跟随专辑封面。", kind: "swatches" },
      { icon: "keyboard", t: "媒体键与控制中心", d: "系统媒体控制，随手可及。", kind: "plain" },
      { icon: "sparkles", t: "识别任务队列", d: "整张歌单，一次加入。", kind: "queue" },
    ],
    editorRows: [
      ["00:12.40", "风把云朵吹成你的模样"],
      ["00:16.85", "我在窗边等一场雨落下"],
      ["--:--.--", "城市的灯一盏一盏亮起"],
    ],
    queueRows: [
      ["浅蓝时刻", "正在识别… 72%"],
      ["潮汐", "排队中"],
      ["蝉鸣", "排队中"],
    ],
  };
})();
