// English edition: captions and UI text (the app's UI, localized so this
// edition shows a single language throughout).
(function () {
  const PV = (window.PV = window.PV || {});

  PV.copy = {
    lang: "en",
    dlWidth: 860,
    title: "LightPlayer Film",

    cap: {
      intro: ["Every song.", "Every film.", "Every lyric."],
      heroTitle: "Light. And capable of everything.",
      heroSub: "A lightweight media player, made for Mac.",
      fmtTitle: "Nearly every format. Just open and play.",
      fmtCols: [
        { t: "Direct Play", d: "Native decoding, no waiting" },
        { t: "Lossless Remux", d: "Video streams copied as is" },
        { t: "Audio Conversion", d: "Decoded to a FLAC cache" },
        { t: "Hardware Transcode", d: "Smooth, hardware encoded" },
      ],
      fmtFoot: "Built-in FFmpeg picks the best way to play, automatically.",
      lyrTitle: "Lyrics that flow with the voice.",
      lyrSub: "Word-by-word highlighting. Tap any line to jump right to it.",
      aiTitle: "No lyrics? Let it listen.",
      aiSub1: "On-device recognition with whisper.cpp, accelerated by Metal on Apple silicon.",
      aiSub2: "Your music never leaves your Mac.",
      dlTitle: "Desktop lyrics, above everything.",
      dlSub: "Close the window. The music plays on from the menu bar.",
      wxTitle: "The weather outside. Now inside.",
      wxSub: "Sun, rain, snow, thunder and starry nights. Raindrops even land on the play bar.",
      libTitle: "Your whole library, beautifully in order.",
      libSub: "Browse by song, album, artist and video. Favorites and playlists, your way.",
      vidTitle: "Movies look stunning, too.",
      vidSub: "Immersive full screen, AI subtitles, screenshots and frame stepping.",
      moreTitle: "And so much more.",
      outroTag: "Light. And capable of everything.",
      outroAvail: "For Mac with Apple silicon",
      outroUrl: "github.com/2001020/LightPlayer",
    },

    player: {
      start: "Play the film",
      play: "Play or pause (Space)",
      mute: "Sound (M)",
      fullscreen: "Full screen (F)",
      record: "Record as a video file",
      recording: "Recording, click to stop",
      hint: "Space to play or pause   ← → to skip   F for full screen",
      noRecord: "Recording is not supported in this browser.",
    },

    song: {
      title: "Light Blue Hour",
      artist: "Cloudfield",
      album: "Between Sun and Rain",
      file: "Cloudfield - Light Blue Hour.flac",
      ext: "FLAC",
      duration: 236,
    },

    // Original lyrics; words are the karaoke timing units.
    lyrics: [
      "The wind is drawing you in the clouds",
      "I wait by the window for the rain",
      "City lights come on one by one",
      "Like the words you never said",
      "In the light blue hour the world goes still",
      "I can hear my heartbeat echo yours",
      "If the light could slow down just a little",
      "I would sing today back to you",
      "Follow the melody through sun and rain",
      "Every line lands right where it belongs",
      "The wind is gone, the clouds remember",
      "Inside the song we slowly glow",
    ],
    splitWords: (line) => line.split(" ").map((w, i, a) => (i < a.length - 1 ? w + " " : w)),

    playlist: [
      "Cloudfield - Light Blue Hour",
      "Cloudfield - Between Sun and Rain",
      "Cloudfield - Shape of Clouds",
      "Cloudfield - Three in the Afternoon",
      "Cloudfield - Letters from Afar",
      "Cloudfield - Saturday Sea",
      "Cloudfield - Take It Slow",
      "Cloudfield - Night Flight",
      "Cloudfield - Paper Planes",
      "Cloudfield - City in the Fog",
    ],

    albums: [
      ["Between Sun and Rain", "Cloudfield"],
      ["Coastline", "White Whale"],
      ["Midnight Radio", "Deep Woods"],
      ["Summer Echoes", "Ash Tree"],
      ["Paper Planes", "Mira Lane"],
      ["City in the Fog", "North Island"],
      ["Under the Neon", "Night Walkers"],
      ["Distant Hills", "Green Field"],
      ["Take It Slow", "South Wind"],
      ["Saturday Sea", "Whale Fall"],
    ],

    songs: [
      ["Light Blue Hour", "Cloudfield", "Between Sun and Rain", "3:56"],
      ["Tides", "White Whale", "Coastline", "4:12"],
      ["2 AM Frequency", "Deep Woods", "Midnight Radio", "3:41"],
      ["Cicadas", "Ash Tree", "Summer Echoes", "3:28"],
      ["Paper Planes", "Mira Lane", "Paper Planes", "3:05"],
      ["City in the Fog", "North Island", "City in the Fog", "5:02"],
      ["Under the Neon", "Night Walkers", "Under the Neon", "4:20"],
      ["Distant Hills", "Green Field", "Distant Hills", "3:47"],
      ["Take It Slow", "South Wind", "Take It Slow", "4:03"],
      ["Saturday Sea", "Whale Fall", "Saturday Sea", "4:36"],
      ["Shape of Clouds", "Cloudfield", "Between Sun and Rain", "3:33"],
      ["Sea Breeze", "White Whale", "Coastline", "3:59"],
    ],

    video: {
      title: "Sunset by the Sea",
      file: "Sunset by the Sea 4K.mkv",
      strategy: "Remuxed playback",
      subs: ["The waves keep coming back", "like a gentle word said again and again", "and the light slowly sinks into the sea"],
    },

    weather: { rain: "Light rain", snow: "Light snow", night: "Clear" },

    menubar: {
      menus: ["File", "Edit", "View", "Window", "Help"],
      clock: "Wed Oct 1  9:30 PM",
      tray: ["Light Blue Hour - Cloudfield", "Pause", "Previous", "Next", "Private Browsing", "Show LightPlayer", "Quit LightPlayer"],
    },

    ui: {
      font: '"SF Pro Text", -apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Inter", "Noto Sans", "Noto Sans SC", "WenQuanYi Zen Hei", sans-serif',
      back: "Back",
      coverHint: "Click to view lyrics",
      playlist: "Playlist",
      count: (n) => `${n} songs`,
      searchFolder: "Search this folder",
      fromFolder: "Current folder",
      handle: ["L", "i", "s", "t"],
      emptyTitle: "No Lyrics",
      emptyText: "No lyrics file with the same name was found next to this song",
      upload: "Upload Lyrics",
      manual: "Create Manually",
      aiRecognize: "Recognize with AI",
      asrStage: "Recognizing…",
      asrDecoding: "Decoding audio…",
      asrNote: "Recognition runs offline on this Mac and never uploads any audio. Longer songs may take a minute or two; keep listening meanwhile.",
      viewAll: "View All Tasks",
      cancel: "Cancel",
      aiBanner: "Recognized by AI and may contain errors",
      review: "Review",
      rerun: "Recognize Again",
      remove: "Remove",
      aiChip: "AI Lyrics",
      nav: ["Songs", "Albums", "Artists", "Videos", "Favorites", "Recently Played"],
      playlistsGroup: "PLAYLISTS",
      userPlaylists: [["Bedtime", 24], ["Commute", 38], ["Lazy Sunday", 17]],
      manageFolders: "Manage Folders",
      search: "Search titles, artists, albums",
      playAll: "Play All",
      shuffle: "Shuffle",
      albumsTitle: "Albums",
      albumsSub: (n) => `${n} albums`,
      songsTitle: "Songs",
      songsSub: "1286 songs, 86 hours 12 minutes",
      cols: ["#", "Title", "Artist", "Album", "Time"],
      privateBadge: "Private",
      dlColor: "Text color",
      speedLabel: "Playback Speed",
      normal: "Normal",
    },

    tiles: [
      { icon: "ab", t: "A-B Loop", d: "Repeat any passage you love.", kind: "ab" },
      { icon: "speed", t: "Playback Speed", d: "0.5× to 3×, pitch preserved.", kind: "speed" },
      { icon: "timer", t: "Sleep Timer", d: "Fades out, then pauses.", kind: "timer" },
      { icon: "clock", t: "Resume Playback", d: "Pick up right where you left off.", kind: "plain" },
      { icon: "incognito", t: "Private Browsing", d: "Opened files leave no history.", kind: "private" },
      { icon: "edit", t: "Lyrics Editor", d: "Tap along to time every line.", kind: "editor" },
      { icon: "subtitles", t: "AI Subtitles", d: "Generate subtitles for any video.", kind: "plain" },
      { icon: "camera", t: "Screenshots", d: "Save the current frame in a click.", kind: "plain" },
      { icon: "film", t: "Frame Stepping", d: "Step through with , and . keys.", kind: "frames" },
      { icon: "image", t: "Cover Colors", d: "The accent follows the album art.", kind: "swatches" },
      { icon: "keyboard", t: "Media Keys", d: "Control Center and media keys, built in.", kind: "plain" },
      { icon: "sparkles", t: "Recognition Queue", d: "Add a whole playlist at once.", kind: "queue" },
    ],
    editorRows: [
      ["00:12.40", "The wind is drawing you in the clouds"],
      ["00:16.85", "I wait by the window for the rain"],
      ["--:--.--", "City lights come on one by one"],
    ],
    queueRows: [
      ["Light Blue Hour", "Recognizing… 72%"],
      ["Tides", "Queued"],
      ["Cicadas", "Queued"],
    ],
  };
})();
